# Generated by Django 5.2.6 on 2025-10-23 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic_status", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="perm",
            unique_together={("user", "content_type", "object_id", "perm")},
        ),
    ]
