# Generated by Django 5.2.6 on 2026-01-22 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("generic_status", "0002_alter_perm_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="perm",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
