# Generated by Django 5.2.6 on 2025-09-26 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must be 2 or 3 uppercase English letters.",
                                regex="^[A-Z]{2,3}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
