# Generated by Django 5.2.6 on 2025-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="flags/"),
        ),
    ]
