# Generated by Django 5.2.6 on 2025-09-25 19:21

from django.db import migrations, models

import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.utils.user_avatar_path
            ),
        ),
    ]
