# Generated by Django 5.2.6 on 2025-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0002_module_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="visible",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=7,
            ),
        ),
    ]
