# Generated by Django 5.2.6 on 2025-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_module_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
