# Generated by Django 5.2.6 on 2025-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='visible',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
