# Generated by Django 5.2.6 on 2025-09-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['original']},
        ),
    ]
