# Generated by Django 5.2.6 on 2025-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_card_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
